# To use Make file you need Arduino-Makefile refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
include ../Arduino-Makefile-master/Arduino.mk
CPPFLAGS += -std=gnu++11
ARDUINO_PORT = /dev/ttyACM0

